test function on controller

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,3 +2,9 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 composer run lint:fix
+exitCode="$?"
+if [ $exitCode != 0 ]; then
+    echo "husky - $hook_name hook exited with code $exitCode (error)"
+    exit $exitCode
+fi
+exit 0
